### ISSUE TITLE
Question: Can this work with a monorepo?

### ISSUE THREAD

**Issue by uglow** [MishaKav/jest-coverage-comment#21]
This looks like a great coverage reporter action! But I didn't see any references to monorepos, which have multiple coverage files to deal with. Is that something you support, or should I look for another tool?

**Comment by MishaKav** [comment]
This is something that I plan to support very soon.

**Comment by MishaKav** [comment]
I've implemented this feature in `v1.0.12`.
you can just pass `multiple-files` [more-info](https://github.com/marketplace/actions/jest-coverage-comment)

example:
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@main
  with:
    multiple-files: |
      My-Title-1, ./data/coverage-summary_1.json
      My-Title-2, ./data/coverage-summary_2.json
```

![image](https://user-images.githubusercontent.com/289035/183769452-99e53ad9-5205-44b7-bba6-c8d481ce5cc4.png)
