### ISSUE TITLE
No comment added when coverage.text is too big

### ISSUE THREAD

**Issue by sandinosaso** [MishaKav/jest-coverage-comment#25]
Issue:

There is no comment added/updated to the PR when the code coverage file result is too big I got the message `Body is too long (maximum is 65536 characters)`. Is there a way to workaround or fix this issue by checking the length and adding 2 comments or more instead of only one?

Here is the result:

<img width="1104" alt="Screenshot 2022-08-15 at 09 18 40" src="https://user-images.githubusercontent.com/466105/184593770-ba6a3824-287a-4b94-8295-3c8484354a46.png">

Thank you

**Comment by MishaKav** [comment]
I will try to think about some fixes in that case (maybe to remove HTML links...), meanwhile I can suggest you a couple of solutions here:
- add `skip-covered`
- hide-summary: true
- report-only-changed-files: true

**Comment by sandinosaso** [comment]
Thank you for the suggestion, where can I use the `skip-covered` flag ... I was merging coverage from multiple coverage files using `istanbul` and this option is not present (I tried also skipFull I tried something like this: `yarn istanbul report --dir coverage --include "coverage/**/coverage-final.json" --skipFull text text-summary json json-summary html` Also, this option is available in jest when I create individual reporters (I think because jest uses (behind the scenes) the lib [instanbul-lib-report](https://www.npmjs.com/package/istanbul-lib-report/v/3.0.0-alpha.2) which support that config.

So in jest I can do 

```
coverageReporters: [
        ['text', { skipFull: true }],
        ['text-summary', { skipFull: true }],
        ['lcov', { projectRoot: './unit-test-report' }],
        ['html', { skipFull: true }]
    ],
 ```
 
 And for individual coverage files this is ok, but when using the `instanbul report` command that option is not available.
 
 I appreciate your help. Thank you

**Comment by sandinosaso** [comment]
Also, using r`eport-only-changed-files: true` does not work in our case, because the number of files that are not 100 percent is still too big, so the comment can not be created 😢

**Comment by MishaKav** [comment]
according to `report-only-changed-files: true`, it's very important on which event you run the action `push/pull_request`:
- `pull_request` - you will see all files that changed in the whole PR
- `push` - you will only see the changes from the last `push` (for example you may update readme in the last push, so you will see the message that "no files were changed")

**Comment by MishaKav** [comment]
Another solution that you can try is: 
- try to add this after the action, it will take the summary and post it in the Summary of the action itself (maybe the summary don't have the limitations)
```yaml
      - name: Add Summary
        uses: actions/github-script@v6
        with:
          script: |
            core.summary.addRaw(${{ steps.coverageComment.outputs. summaryHtml }}).write()
```

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/289035/184983718-cde44112-a260-4433-911a-7b43ea320c05.png">

P.S. I will try to add some property that will remove the html-links that took a lot of space...

**Comment by MishaKav** [comment]
add new properties that should help you #26 :
- `remove-links-to-files: true`
- `remove-links-to-lines: true`

it will significantly reduce comment length which is useful in large reports.

![image](https://user-images.githubusercontent.com/289035/185572824-44782b8e-e2ef-42a3-b06a-5b16e969a9d5.png)

Try to use the latest version 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@main
  with:
    remove-links-to-files: true
    remove-links-to-lines: true
```
or 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@v1.0.14
  with:
    remove-links-to-files: true
    remove-links-to-lines: true
```
