### ISSUE TITLE
Adding Feature: Multiple coverage test

### ISSUE THREAD

**Issue by blankhat1610** [MishaKav/jest-coverage-comment#33]
Hi, first of all I love this action! However, I want to write multiple coverage acording to my test. I suggest the summary, junit, coverage details must be an array to show all coverage of test. Thank you!

**Comment by MishaKav** [comment]
Can you provide please an example of what you mean? I'm not. sure that I get what you mean.

**Comment by blankhat1610** [comment]
Expectd: <img width="921" alt="image" src="https://user-images.githubusercontent.com/57515909/195803420-e45fbfb1-a087-4782-aa45-2782df264810.png">
Unfortunately I've been receive a NaN errors in Junit, hope you can fix it.

**Comment by MishaKav** [comment]
1. currently the action support only a single file or multiple report for `json-sumamry`. I don't think that I will add this feature at all. 
GitHub comments are very limited, especially when the action posts rich HTML with links etc, so sometimes that **is not enough** space even for one report.

I can suggest you try running this action twice (each time for a different report) and pass the `create-new-comment: true`, in this way it should post you 2 different reports (2 different comments)

2. I think, I may add in the future `multiple-junit-files` to support `junit` report for multiple files.

3. it would be great if you could share the Junit file with me so that reproducing the `NaN` bug will be faster.

**Comment by blankhat1610** [comment]
Ahhh, I missed the `create-new-comment`. Thank you very much
> it would be great if you could share the Junit file with me so that reproducing the NaN bug will be faster.
Sorry that I couldn't share the Junit file because of the privacy problem, but the errors in those file only have "0" string and didn't have any strange value.
Thank you for your detail answer, wish you have a good night.

**Comment by MishaKav** [comment]
can you maybe share just the value of the `errors`, it should look like
```XML
<testsuites name="jest tests" tests="6" failures="0" errors="0" time="0.732"></testsuites>
```
my function to parse these values is `Number(main.errors)`

when I test values such `''` or `0`. it works fine, so I can't understand why it got `NaN`

**Comment by blankhat1610** [comment]
Yeah, I'm not sure what's the problem either
```
<testsuite name="Test usecase" errors="0" failures="0" skipped="0" timestamp="2022-10-14T10:37:56" time="8.116" tests="25">
```
the `errors` i've got is all the same like this, I'm also wondering why it happened

**Comment by MishaKav** [comment]
can you please copy one value above? It should be testsuite**s** and not testsuite

**Comment by blankhat1610** [comment]
Ah, so you use the testsuites to get the errors, but my overall testsuites not have errors field
```
<testsuites name="jest tests" tests="234" failures="0" time="13.561"></testsuites>
```

**Comment by MishaKav** [comment]
Now I found an issue. It is because the `jest-junit@10.0.0` does not provide a summary of the `errors` field.
I release the fix for that, try to use the latest version:
 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@main
```
or 
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@v1.0.17
```

**Comment by MishaKav** [comment]
I release a new feature that you request of supporting multiple JUnit files.
You can read more about this in the main [readme](https://github.com/marketplace/actions/jest-coverage-comment#:~:text=workflow%20that%20uses-,multiple%20files%20mode)

```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@main
  with:
    multiple-junitxml-files: |
      My-Title-1, ./coverage_1/junit.xml
      My-Title-2, ./coverage_2/junit.xml
```

or


```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@v1.0.18
  with:
    multiple-junitxml-files: |
      My-Title-1, ./coverage_1/junit.xml
      My-Title-2, ./coverage_2/junit.xml
```
