### ISSUE TITLE
Redundancy Summary table

### ISSUE THREAD

**Issue by blankhat1610** [MishaKav/jest-coverage-comment#36]
Issue: The result have a summary on the top, and it's not quite right to display that. Could you fix it?
<img width="914" alt="image" src="https://user-images.githubusercontent.com/57515909/195999923-b647cf02-3b65-443e-be06-be80f048993b.png">
My code:
```yaml
uses: MishaKav/jest-coverage-comment@main
with:
  multiple-files: |
    Test 1, ./coverage-1/coverage-summary.json
    Test 2, ./coverage-2/coverage-summary.json
  multiple-junitxml-files: |
    Test 1, ./coverage-1/junit.xml
    Test 2, ./coverage-2/junit.xml
  coverage-path: ./coverage-2/coverage.txt
```
Thank you
