### ISSUE TITLE
Uncovered line link pointing to invalid page

### ISSUE THREAD

**Issue by TobiasGoetz** [MishaKav/jest-coverage-comment#57]
## Expected Behavior
Clicking the line numbers in the added comment shows lines not covered by tests in the code.

## Current Behavior
Clicking on line numbers opens another github page but that says: "The *** repository doesn't contain the **/file.js path in '6074*****679594'"

## Steps to Reproduce
1. Have a private repo
2. Have 2 branches (main, exploration)
3. Have basically no files or code on the main branch and all on exploration
4. Open pull request from exploration to main that triggers the action
5. Have uncovered lines in your repo
6. Let action create coverage comment
7. Click uncovered line number in comment
8. See issue

## Screenshots
![image](https://user-images.githubusercontent.com/26843910/210315614-c2a457c4-12f5-41cf-a4cc-e7f772349c15.png)
![image](https://user-images.githubusercontent.com/26843910/210315768-e2b74577-6e40-458d-a081-ee3fac2dea21.png)

**Comment by MishaKav** [comment]
I don't succeed to reproduce the issue, can you please share it with me:
- all settings that you pass to `uses: MishaKav/jest-coverage-comment@main` 
- do you know if the link to the file works? or it doesn't work either?
- can you share with me the generated link for some lines? (you can replace the sensitive data if you want with some `xxx`)

**Comment by TobiasGoetz** [comment]
> all settings that you pass to uses: MishaKav/jest-coverage-comment@main

My workflow includes the following step for generating the comment
```yml
- name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          coverage-path: ./coverage.txt
          junitxml-path: ./coverage/junit.xml
          title: Test Summary
          summary-title: Summary
          junitxml-title: Unit Tests
````

> do you know if the link to the file works? or it doesn't work either?

The link to the file doesn't work either.

> can you share with me the generated link for some lines? (you can replace the sensitive data if you want with some xxx)

Link to the file: `https://github.com/xxx/xxx/blob/e461ec8da9e75b57b81231ccf647baa300b9b6e5/xxx/app.js`
Link to the lines: `https://github.com/xxx/xxx/blob/e461ec8da9e75b57b81231ccf647baa300b9b6e5/xxx/routes/business.js#L79`

I forgot to mention that I am running this in a private organization repo and not my private one.
Don't know if that may influence the result at all.

**Comment by MishaKav** [comment]
- can you share with me the link for the file `app.js`? (what should be instead `xxx` before the `app.js`., it some directory? maybe some prefix? 
this how simple link to some of current repo file looks like `https://github.com/MishaKav/jest-coverage-comment/blob/d12e14b4f20d7075892280420157193cae774e08/package.json`

**Comment by TobiasGoetz** [comment]
- The first `xxx` stands for the organization name
- The second `xxx` stands for the repository name

**Comment by TobiasGoetz** [comment]
The issue seems to be the last(third) `xxx`.
When I remove that one the link works.

**Comment by MishaKav** [comment]
yes, looks like this is the problem, the action already supports this kind of problem. 
You just need to path the prefix directory `coverage-path-prefix` :

```YAML
- name: Jest Coverage Comment
    uses: MishaKav/jest-coverage-comment@main
    with:
      # your cofings....
      coverage-path-prefix: XXX
```
