### ISSUE TITLE
Report table is void

### ISSUE THREAD

**Issue by DavidBernal** [MishaKav/jest-coverage-comment#7]
Hello, I'm trying to configure this action, but the comment has a void table:

![image](https://user-images.githubusercontent.com/4368806/164022454-536b16d2-6b7a-48ba-9c4f-e9adbbf88720.png)

The logs seem correct:

![image](https://user-images.githubusercontent.com/4368806/164024085-c8be97aa-a70b-4e8e-8a3b-3826f3d67977.png)

And coverage file has content for sure.

**Comment by DavidBernal** [comment]
The coverage-sumary.json is like: 
```json
{
  "total": {
    "lines": {
      "total": 187,
      "covered": 0,
      "skipped": 0,
      "pct": 0
    },
    "statements": {
      "total": 193,
      "covered": 0,
      "skipped": 0,
      "pct": 0
    },
    "functions": {
      "total": 50,
      "covered": 0,
      "skipped": 0,
      "pct": 0
    },
    "branches": {
      "total": 34,
      "covered": 0,
      "skipped": 0,
      "pct": 0
    },
    "branchesTrue": {
      "total": 0,
      "covered": 0,
      "skipped": 0,
      "pct": 0
    }
  },
  ... files coverage ... 
}
```
I can't put the full coverage with files because is a enterprise project. 

Action looks like:
```yaml
- name: Jest coverage comment
  uses: MishaKav/jest-coverage-comment@main
  with:
    coverage-summary-path: coverage/coverage-summary.json
```
