### ISSUE TITLE
Does not create output / comment

### ISSUE THREAD

**Issue by mindrunner** [MishaKav/jest-coverage-comment#70]
Something seems broken and I cannot figure out what. It seems like my coverage files were parsed correctly, but then  there is no output generated, nor is a comment posted to my PR. What am I missing here?

```
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Coverage
          multiple-files: |
            Unit Test, ./build/test/unit/coverage/coverage-summary.json
            Integration Test 1, ./build/test/int/coverage/coverage-summary-1.json
            Integration Test 2, ./build/test/int/coverage/coverage-summary-2.json
            Integration Test 3, ./build/test/int/coverage/coverage-summary-3.json
            Integration Test 4, ./build/test/int/coverage/coverage-summary-4.json
          multiple-junitxml-files: |
            Unit Test, ./build/test/unit/junit.xml
            Integration Test 1, ./build/test/int/junit-1.xml
            Integration Test 2, ./build/test/int/junit-2.xml
            Integration Test 3, ./build/test/int/junit-3.xml
            Integration Test 4, ./build/test/int/junit-4.xml
```
![image](https://github.com/MishaKav/jest-coverage-comment/assets/1413542/66490858-6166-44fa-8ef9-0103606f556e)

```
      - name: Check the output coverage
        run: |
          echo "Summary Report"
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary Html - ${{ steps.coverageComment.outputs.summaryHtml }}"

          echo "JUnit Report"
          echo "tests - ${{ steps.coverageComment.outputs.tests }}"
          echo "skipped - ${{ steps.coverageComment.outputs.skipped }}"
          echo "failures - ${{ steps.coverageComment.outputs.failures }}"
          echo "errors - ${{ steps.coverageComment.outputs.errors }}"
          echo "time - ${{ steps.coverageComment.outputs.time }}"

          echo "Coverage Report"
          echo "lines - ${{ steps.coverageComment.outputs.lines }}"
          echo "branches - ${{ steps.coverageComment.outputs.branches }}"
          echo "functions - ${{ steps.coverageComment.outputs.functions }}"
          echo "statements - ${{ steps.coverageComment.outputs.statements }}"
          echo "coverage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "color - ${{ steps.coverageComment.outputs.color }}"
          echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
```

![image](https://github.com/MishaKav/jest-coverage-comment/assets/1413542/664dcd4d-5f2e-4667-b315-44975776f6b4)

**Comment by MishaKav** [comment]
You can't see the full output, because you missed an Id,  try to add it:
```yalm
- name: Jest Coverage Comment
   id: coverageComment
   uses: MishaKav/jest-coverage-comment@main
```

> why its not posted posted to my PR
I need to see the full workflow and by which trigger you try to run it.

**Comment by mindrunner** [comment]
Alright, some issues are solved. But not all of them. It seems like a comment is created as soon as I add the `pull_request` trigger. On `push` trigger, it does not work. Would that be expected? What I want to achieve is:

1) run test suite on every push
2) post results in open PR (if one exist)

If I have `pull_request` and `push` trigger. Tests are ran twice when I push new code to an open PR, which seem senseless to me.

Other issue is the `coverage-path` parameter. I am supposed to pass the `stdout` of jest there, right? If I do pass it on to `tee` as you do in your example, I only get an empty file. If I also redirect `stderr`, I get the content I would expect, but parsing seems broken:
```
File read successfully "./build/test/unit/out.txt"
Coverage Report
  coverage: 0
  color: red
  branches: 0
  functions: 0
  lines: 0
  statements: 0
  coverageHtml: <details><summary>Coverage Report (<b>0%</b>)</summary><table><tr><th>File</th><th>% Stmts</th><th>% Branch</th><th>% Funcs</th><th>% Lines</th><th>Uncovered Line #s</th></tr><tbody>&nbsp;</tbody></table></details>
```

Simplified example:

```
name: Test
on:
  - push
  - pull_request
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn-install

      - name: Create coverage directory
        run: mkdir -p build/test/unit/

      - name: Unit
        run: yarn test:unit --coverage 2>&1 | tee ./build/test/unit/out.txt

      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          unique-id-for-comment: unit
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Unit Test Coverage
          coverage-path: ./build/test/unit/out.txt
          coverage-summary-path: ./build/test/unit/coverage/coverage-summary.json
          junitxml-path: ./build/test/unit/junit.xml

```
