### ISSUE TITLE
multiple-files seems not working 

### ISSUE THREAD

**Issue by Chongfuyu** [MishaKav/jest-coverage-comment#73]
Using multiple-files for coverage-summary json and it will shows not exist, however, when using the coverage-summary-path for each of them works well.

**Comment by MishaKav** [comment]
can you please share more details about this issue? your `jest-coverage-comment` configuration, some logs from it, maybe some screenshots from output or warning that you have...

**Comment by Chongfuyu** [comment]
while calling 3 times for each packages works 

```
      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: ${{ github.workspace }}/packages/XXXX/coverage/coverage-summary.json
          report-only-changed-files: true
```
However, when using multiple-files it will show error for coverage-summary.json not exist

```
      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          multiple-files: |
               ReportA, ${{ github.workspace }}/packages/A/coverage/coverage-summary.json
               ReportB, ${{ github.workspace }}/packages/B/coverage/coverage-summary.json
          report-only-changed-files: true
```
