### ISSUE TITLE
Dynamic multiple-files issue

### ISSUE THREAD

**Issue by SirPhemmiey** [MishaKav/jest-coverage-comment#87]
It's sortof a duplicate to [this](https://github.com/MishaKav/jest-coverage-comment/issues/72) but the answer there didn't help me. 

here's a snippet of my workflow

```
- name: Prepare coverage input
   id: prepare-coverage-input
    run: |
        input=""
         for dir in coverage-report/*/*/coverage-summary.json; do
          appname=$(basename $(dirname $(dirname $dir)))
          input="${input}${appname}, ${dir}\n"
          done
          echo "${input}" > coverage-input.txt

  - name: Show coverage input content
     run: cat coverage-input.txt

 - name: Read coverage-inputs.txt
    id: multiplefiles
    uses: jaywcjlove/github-action-read-file@main
    with:
      path: coverage-input.txt

- name: Jest Coverage Comment
   uses: MishaKav/jest-coverage-comment@main
    if: github.event_name == 'pull_request'
    with:
      multiple-files: ${{ steps.multiplefiles.outputs.content }}
```

I am getting this error when i am not even passing `/coverage/coverage-summary.json`:
<img width="894" alt="Screenshot 2024-05-14 at 17 06 51" src="https://github.com/MishaKav/jest-coverage-comment/assets/22390818/0ab952a3-fc1b-4343-a4ed-86d6865053cb">

This is also the content of `coverage-inputs.txt` to show that it's not empty
<img width="1057" alt="Screenshot 2024-05-14 at 17 08 37" src="https://github.com/MishaKav/jest-coverage-comment/assets/22390818/e2a63e32-895c-498b-80bc-790d5a222ac2">

Looking forward to your help on this, thanks!

**Comment by SirPhemmiey** [comment]
@MishaKav

**Comment by MishaKav** [comment]
From what I see in the screenshot, your file contains `\n` **as text** and not as a `break-line`.
Try to play with your file generation.

**Comment by SirPhemmiey** [comment]
Hi @MishaKav, i fixed the format and it's still the same


<img width="1156" alt="Screenshot 2024-05-15 at 11 09 20" src="https://github.com/MishaKav/jest-coverage-comment/assets/22390818/7a87250b-0b80-451c-8ba6-0cee5eceb450">

**Comment by MishaKav** [comment]
The paths you provide start with "coverage-report/...", as you can see in #72 the paths should be relative or be absolute or start with "./coverage-report/..." or similar. Please try this.

**Comment by SirPhemmiey** [comment]
Happy to say it worked when i used another file reader github action. 

Here's the full working version (without formatting the YAML) for anyone having the same issue

```
- name: Prepare coverage input
        id: prepare-coverage-input
        run: |
          input=""
          for dir in coverage-report/*/*/coverage-summary.json; do
            appname=$(basename $(dirname $(dirname $dir)))
            input="${input}${appname}, ${dir}\n"
          done
          printf "${input}" > coverage-input.txt

      - name: Read coverage-inputs.txt
        id: multiplefiles
        uses: juliangruber/read-file-action@v1
        with:
          path: coverage-input.txt

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        if: github.event_name == 'pull_request'
        with:
          title: Test Coverage Summary
          summary-title: Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          coverage-title: Coverage Analysis
          coverage-path: coverage-input.txt
          multiple-files: ${{ steps.multiplefiles.outputs.content }}
```

**Comment by SirPhemmiey** [comment]
Thank you @MishaKav !

**Comment by MishaKav** [comment]
Thank you for sharing the whole solution.

**Comment by SirPhemmiey** [comment]
Hi @MishaKav, quick question. 

When using the multiple files approach can i still put a value to `coverage-path`? if yes, what should the value be?

**Comment by MishaKav** [comment]
Yes, you can using `multiple-files` with `coverage-path`. In the main readme, you have an [example](https://github.com/MishaKav/jest-coverage-comment?tab=readme-ov-file#coverage-report).
It can be something like this:

```yaml
- name: Run Tests
  run: npm run coverage | tee ./coverage.txt && exit ${PIPESTATUS[0]}

- name: Jest Coverage Comment
  uses: MishaKav/jest-coverage-comment@main
  with:
    coverage-path: ./coverage.txt
    multiple-files: |
      My-Title-1, ./coverage/coverage-summary.json
      My-Title-2, ./coverage/coverage-summary.json
```

The result will be as in the screenshot below:
<img width="854" alt="image" src="https://github.com/MishaKav/jest-coverage-comment/assets/289035/a9a7c72b-b135-48c9-b191-9d1fb8fc3646">
