### ISSUE TITLE
How to continue to this action after a test failure?

### ISSUE THREAD

**Issue by ChrisMBarr** [MishaKav/jest-coverage-comment#93]
This action seems to work great when there are no test failures, but when I do have a failure it is never hit since my testing step fails and exits.  How to I make it always continue on to always report regardless?

Here is my action setup
```yml
name: Pull Request Sanity Check

on:
  pull_request:
    paths-ignore: ['.vscode/**', 'README.md', '.*']

permissions:
  contents: write

jobs:
  pr-sanity-check:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      # Preparation ----------------------------------------------------
      - name: ⏬ Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 💻 Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install Packages
        run: npm ci

      # Building ----------------------------------------------------
      - name: 🛠️ Build UI (Angular)
        working-directory: app
        run: npm run build

      - name: 🛠️ Build Server (NestJS)
        working-directory: server-nest
        run: npm run build

      # Unit Testing ----------------------------------------------------
      - name: 🧪 Unit Test Runner (NestJS) 🌮
        working-directory: server-nest
        run: npx jest --coverage --coverageReporters=text --coverageReporters=json-summary --reporters=jest-junit --reporters=github-actions && exit ${PIPESTATUS[0]}

      - name: 🧪 Unit Test Reporter
        uses: MishaKav/jest-coverage-comment@main
        with: #we can have this report on code coverage in multiple projects
          title: Code Coverage Report
          multiple-files: |
            NestJS Server, ./server-nest/coverage/coverage-summary.json
          multiple-junitxml-files: |
            NestJS Server, ./server-nest/junit.xml
```

And this is what I see in the output

![image](https://github.com/MishaKav/jest-coverage-comment/assets/463685/fbfeacd4-58e8-436a-9132-25a60a1e7887)

The key part to focus on here I suppose is how I run my tests, which is this:
```
npx jest --coverage --coverageReporters=text --coverageReporters=json-summary --reporters=jest-junit --reporters=github-actions && exit ${PIPESTATUS[0]}
```

I've tried forcing `&& exit 0` at the end as well, but even that results in it reporting `Process completed with exit code 1.` and I dont understand why

![image](https://github.com/MishaKav/jest-coverage-comment/assets/463685/e5d487df-5563-4155-bff8-c723cd772b09)

**Comment by ChrisMBarr** [comment]
It's been a few weeks since I created this, can anyone provide the info?  This feels pretty basic, I mean this is entirely what this project is about - reporting test failures. What do I need to do to make that happen?

**Comment by MishaKav** [comment]
The purpose of the current action is to generate the tests `report` from `provided files`. 
The problem is that you **don't reach** the step of the current actions because the previous step is failing.
I suggest you try the following:

1.  add `continue-on-error: true` - it will continue to next step, even if the current is failing
```yaml
- name: 🧪 Unit Test Runner (NestJS) 🌮
  working-directory: server-nest
  continue-on-error: true
  run: npx jest --coverage --coverageReporters=text --coverageReporters=json-summary --reporters=jest-junit --reporters=github-actions
```

2. add `if: ${{ always() }}` the will always execute the step of current action:
```yaml
- name: 🧪 Unit Test Reporter
  uses: MishaKav/jest-coverage-comment@main
  if: ${{ always() }}
  with: #we can have this report on code coverage in multiple projects
    title: Code Coverage Report
    multiple-files: |
      NestJS Server, ./server-nest/coverage/coverage-summary.json
    multiple-junitxml-files: |
      NestJS Server, ./server-nest/junit.xml
```
