### ISSUE TITLE
Bug: Coverage Comment is ignoring property create-new-comment

### ISSUE THREAD

**Issue by mluizaa00** [MishaKav/jest-coverage-comment#95]
Hello,
I currently have the following configuration:

```yml
      - name: Jest Coverage Comment File
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          title: Test Coverage (Files)
          coverage-path: ./app/apps/project/coverage.txt
          create-new-comment: false
          coverage-title: Project
          report-only-changed-files: true
```

With the property `create-new-comment` disabled. But my pull requests always have a **duplicated comment** of the coverage after each commit, as if it was ignoring this property.

Can someone help? Is this an issue with the configuration or with the plugin itself?
